amcl:
  ros__parameters:
    laser_max_range: -1.0 # Use value reported in laser scan
    laser_min_range: -1.0 # Use value reported in laser scan

bt_navigator:
  ros__parameters:
    global_frame: map
    robot_base_frame: base_link
    odom_topic: odom
    navigators: ["navigate_to_pose"]

    navigate_to_pose:
      plugin: "nav2_bt_navigator/NavigateToPoseNavigator"

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      rolling_window: True
      width: 2
      height: 2
      resolution: 0.04
      robot_radius: 0.22 # TODO(CF-823): Replace with truck's measured footprint radius
      always_send_full_costmap: True
      origin_x: -1.0
      origin_y: -1.0
      plugins: ["obstacle_layer", "inflation_layer"]
      filters: ["keepout_filter"]

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan

        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.70

      keepout_filter:
        plugin: "nav2_costmap_2d::KeepoutFilter"
        enabled: True
        filter_info_topic: "/costmap_filter_info"

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      robot_radius: 0.22 # TODO(CF-823): Replace with truck's measured footprint radius
      resolution: 0.04
      track_unknown_space: true
      always_send_full_costmap: True
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      filters: ["keepout_filter"]

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan

        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.7

      keepout_filter:
        plugin: "nav2_costmap_2d::KeepoutFilter"
        enabled: True
        filter_info_topic: "/costmap_filter_info"

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    planner_plugins: ["GridBased"]

    GridBased:
      plugin: "nav2_smac_planner/SmacPlannerHybrid"
      tolerance: 0.5
      allow_unknown: false

controller_server:
  ros__parameters:
    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["general_goal_checker"]
    controller_plugins: ["FollowPath"]

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"

    general_goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"

    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      use_rotate_to_heading: False

route_server:
  ros__parameters:
    graph_filepath: "/home/ubuntu/c1t_ws/src/navigation2/nav2_route/graphs/chub.geojson"
    boundary_radius_to_achieve_node: 1.0
    radius_to_achieve_node: 2.0
    edge_cost_functions: ["DistanceScorer", "CostmapScorer"]
    operations: ["AdjustSpeedLimit", "ReroutingService", "CollisionMonitor"]

    ReroutingService:
      plugin: "nav2_route::ReroutingService"

    AdjustSpeedLimit:
      plugin: "nav2_route::AdjustSpeedLimit"

    CollisionMonitor:
      plugin: "nav2_route::CollisionMonitor"
      max_collision_dist: 1.0

    DistanceScorer:
      plugin: "nav2_route::DistanceScorer"

    CostmapScorer:
      plugin: "nav2_route::CostmapScorer"

costmap_filter_info_server:
  ros__parameters:
    type: 0
    filter_info_topic: "/costmap_filter_info"
    mask_topic: "/keepout_filter_mask"
    base: 0.0
    multiplier: 1.0

filter_mask_server:
  ros__parameters:
    frame_id: "map"
    topic_name: "/keepout_filter_mask"

scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: footprint_filter
      type: laser_filters/LaserScanFootprintFilter
      params:
        inscribed_radius: 1.0
